# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_WwRPsU3E2Iqt6bqBzyShAhISfjrNZy
"""

# app.py

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load model and symptom labels
model = joblib.load('model.pkl')
symptom_labels = joblib.load('symptom_labels.pkl')

# Load disease dictionary
disease_info = pd.read_csv("disease_info.csv")

st.title("AI Health Assistant")
st.write("Select your symptoms to get a possible diagnosis.")

# Multiselect
selected_symptoms = st.multiselect("Select your symptoms", sorted(symptom_labels))

if st.button("Predict"):
    if not selected_symptoms:
        st.warning("Please select at least one symptom.")
    else:
         # Convert symptoms to input vector
        input_data = [1 if s in selected_symptoms else 0 for s in symptom_labels]
        prediction = model.predict([input_data])[0]

        # Display prediction
        st.success(f"Possible diagnosis: **{prediction}**")

        # Display additional info
        result = disease_info[disease_info["Disease"].str.lower() == prediction.lower()]

        if not result.empty:
            st.markdown(f"**Common Symptoms:** {result['Symptoms'].values[0].split(','))}")
        else:
            st.info("No additional information available for this disease.")
