# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x_WwRPsU3E2Iqt6bqBzyShAhISfjrNZy
"""

# app.py

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Load model and symptom labels
model = joblib.load('model.pkl')
symptom_labels = joblib.load('symptom_labels.pkl')

st.title("AI Health Assistant")
st.write("Select your symptoms to get a possible diagnosis.")

# Multiselect
selected_symptoms = st.multiselect("Select your symptoms", sorted(symptom_labels))

if st.button("Predict"):
    if not selected_symptoms:
        st.warning("Please select at least one symptom.")
    else:
        input_data = [1 if symptom in selected_symptoms else 0 for symptom in symptom_labels]
        prediction = model.predict([input_data])
        st.success(f"Possible diagnosis: **{prediction[0]}**")